#!/usr/bin/env bash
#
# Mints a self-signed CA and loads it into the `confluent` namespace as the
# secret `ca-pair-sslcerts`.
#
# CFK's `tls.autoGeneratedCerts: true` looks for exactly that secret name and
# uses the key pair to issue per-component server certificates, with SANs
# covering the in-cluster service names. The public half of this same CA is
# later handed to the log collector so it can verify the brokers.
#
# The private key never leaves ./generated, which is gitignored. Re-running is
# a no-op unless --force is passed: regenerating the CA would invalidate every
# certificate CFK has already issued.
set -euo pipefail

NAMESPACE="${NAMESPACE:-confluent}"
OUT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/generated"
DAYS="${CA_DAYS:-3650}"
FORCE=0

[[ "${1:-}" == "--force" ]] && FORCE=1

mkdir -p "$OUT_DIR"

if [[ -f "$OUT_DIR/ca-key.pem" && $FORCE -eq 0 ]]; then
  echo "CA already present at $OUT_DIR (pass --force to regenerate)"
else
  echo "Generating CA key pair in $OUT_DIR"
  openssl req -new -x509 -nodes \
    -newkey rsa:2048 \
    -days "$DAYS" \
    -keyout "$OUT_DIR/ca-key.pem" \
    -out "$OUT_DIR/ca.pem" \
    -subj "/C=US/ST=CA/L=MountainView/O=Confluent/OU=Operator/CN=ocp-confluent-logging-ca" \
    -addext "basicConstraints=critical,CA:TRUE" \
    -addext "keyUsage=critical,keyCertSign,cRLSign,digitalSignature"
fi

echo "Loading CA into secret ca-pair-sslcerts (namespace: $NAMESPACE)"
oc create secret tls ca-pair-sslcerts \
  --cert="$OUT_DIR/ca.pem" \
  --key="$OUT_DIR/ca-key.pem" \
  --namespace "$NAMESPACE" \
  --dry-run=client -o yaml | oc apply -f -

echo "OK"
